packages:
  - .
allowBuilds:
  '@parcel/watcher': true
  '@tailwindcss/oxide': true
  esbuild: true
  unrs-resolver: true
overrides:
  brace-expansion: ^2.1.4
  nanoid: ^6.0.1
  h3: ^1.15.9
  '@ai-sdk/provider-utils': ^5.0.27
