allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
  "@tailwindcss/oxide": true
minimumReleaseAgeExclude:
  - '@ai-sdk/amazon-bedrock@5.0.2'
  - '@ai-sdk/anthropic@4.0.1'
  - '@ai-sdk/gateway@4.0.4'
  - '@ai-sdk/openai-compatible@3.0.1'
  - '@ai-sdk/openai@4.0.2'
  - '@ai-sdk/provider-utils@5.0.1'
  - ai@7.0.4
  - lucide-react@1.22.0
verifyDepsBeforeRun: false
