import type { CodeEntry } from "@/lib/contract";

// 40 real, common outpatient CPT codes. typicalFeeCents is a realistic US
// outpatient billed charge per unit (integer cents), used for outlier detection.
export const CPT_CODES: CodeEntry[] = [
  {
    code: "99202",
    description: "Office/outpatient visit, new patient, straightforward MDM",
    synonyms: ["new patient visit lvl 2", "office visit, new patient", "new pt visit level 2"],
    typicalFeeCents: 12500,
  },
  {
    code: "99203",
    description: "Office/outpatient visit, new patient, low MDM",
    synonyms: ["new patient visit lvl 3", "office visit, new patient, level 3", "new pt visit level 3"],
    typicalFeeCents: 17500,
  },
  {
    code: "99204",
    description: "Office/outpatient visit, new patient, moderate MDM",
    synonyms: ["new patient visit lvl 4", "office visit, new patient, level 4", "new pt visit level 4"],
    typicalFeeCents: 25000,
  },
  {
    code: "99205",
    description: "Office/outpatient visit, new patient, high MDM",
    synonyms: ["new patient visit lvl 5", "office visit, new patient, level 5", "new pt visit level 5"],
    typicalFeeCents: 32500,
  },
  {
    code: "99211",
    description: "Office/outpatient visit, established patient, minimal",
    synonyms: ["est patient visit lvl 1", "nurse visit", "office visit, established, level 1"],
    typicalFeeCents: 5000,
  },
  {
    code: "99212",
    description: "Office/outpatient visit, established patient, straightforward MDM",
    synonyms: ["est patient visit lvl 2", "office visit, established, level 2", "est pt visit level 2"],
    typicalFeeCents: 9500,
  },
  {
    code: "99213",
    description: "Office/outpatient visit, established patient, low MDM",
    synonyms: ["est patient visit lvl 3", "office visit, established", "est pt visit level 3"],
    typicalFeeCents: 18000,
  },
  {
    code: "99214",
    description: "Office/outpatient visit, established patient, moderate MDM",
    synonyms: ["est patient visit lvl 4", "office visit, established, level 4", "est pt visit level 4"],
    typicalFeeCents: 26000,
  },
  {
    code: "99215",
    description: "Office/outpatient visit, established patient, high MDM",
    synonyms: ["est patient visit lvl 5", "office visit, established, level 5", "est pt visit level 5"],
    typicalFeeCents: 35000,
  },
  {
    code: "99385",
    description: "Initial preventive medicine evaluation, new patient, 18-39 years",
    synonyms: ["new patient preventive exam 18-39", "initial preventive visit, adult", "new pt physical 18-39"],
    typicalFeeCents: 22000,
  },
  {
    code: "99386",
    description: "Initial preventive medicine evaluation, new patient, 40-64 years",
    synonyms: ["new patient preventive exam 40-64", "initial preventive visit 40-64", "new pt physical 40-64"],
    typicalFeeCents: 25000,
  },
  {
    code: "99394",
    description: "Periodic preventive medicine reevaluation, established patient, 12-17 years",
    synonyms: ["adolescent well visit", "annual exam 12-17", "well child visit, adolescent"],
    typicalFeeCents: 18000,
  },
  {
    code: "99395",
    description: "Periodic preventive medicine reevaluation, established patient, 18-39 years",
    synonyms: ["annual physical 18-39", "preventive exam, established, 18-39", "annual wellness 18-39"],
    typicalFeeCents: 20000,
  },
  {
    code: "99396",
    description: "Periodic preventive medicine reevaluation, established patient, 40-64 years",
    synonyms: ["annual physical 40-64", "preventive exam, established, 40-64", "annual wellness 40-64"],
    typicalFeeCents: 22000,
  },
  {
    code: "36415",
    description: "Collection of venous blood by venipuncture",
    synonyms: ["venipuncture", "blood draw", "phlebotomy"],
    typicalFeeCents: 1500,
  },
  {
    code: "80053",
    description: "Comprehensive metabolic panel",
    synonyms: ["CMP", "comprehensive metabolic panel", "chem panel"],
    typicalFeeCents: 4500,
  },
  {
    code: "80061",
    description: "Lipid panel",
    synonyms: ["lipid panel", "cholesterol panel", "lipids"],
    typicalFeeCents: 5000,
  },
  {
    code: "85025",
    description: "Complete blood count (CBC) with automated differential",
    synonyms: ["CBC", "CBC with diff", "complete blood count"],
    typicalFeeCents: 3500,
  },
  {
    code: "83036",
    description: "Hemoglobin A1c",
    synonyms: ["A1c", "HbA1c", "hemoglobin A1c", "glycated hemoglobin"],
    typicalFeeCents: 4500,
  },
  {
    code: "84443",
    description: "Thyroid stimulating hormone (TSH)",
    synonyms: ["TSH", "thyroid stimulating hormone", "thyroid panel"],
    typicalFeeCents: 6000,
  },
  {
    code: "81002",
    description: "Urinalysis, non-automated, without microscopy",
    synonyms: ["urinalysis", "UA", "urine dip", "dipstick urinalysis"],
    typicalFeeCents: 1200,
  },
  {
    code: "82947",
    description: "Glucose, quantitative, blood",
    synonyms: ["blood glucose", "glucose test", "fasting glucose"],
    typicalFeeCents: 1500,
  },
  {
    code: "87880",
    description: "Streptococcus group A rapid antigen test",
    synonyms: ["rapid strep", "strep test", "rapid strep A test"],
    typicalFeeCents: 3000,
  },
  {
    code: "87804",
    description: "Influenza rapid antigen test",
    synonyms: ["rapid flu", "flu test", "rapid influenza test"],
    typicalFeeCents: 3500,
  },
  {
    code: "90471",
    description: "Immunization administration, one vaccine",
    synonyms: ["vaccine admin", "immunization admin", "vaccine administration, first"],
    typicalFeeCents: 3000,
  },
  {
    code: "90472",
    description: "Immunization administration, each additional vaccine",
    synonyms: ["vaccine admin, additional", "immunization admin, each addl", "second vaccine admin"],
    typicalFeeCents: 1800,
  },
  {
    code: "90686",
    description: "Influenza virus vaccine, quadrivalent, preservative free, IM",
    synonyms: ["flu vaccine", "flu shot", "quadrivalent influenza vaccine"],
    typicalFeeCents: 3200,
  },
  {
    code: "90715",
    description: "Tdap vaccine, 7 years or older, IM",
    synonyms: ["Tdap", "tetanus booster", "Tdap vaccine"],
    typicalFeeCents: 6500,
  },
  {
    code: "90732",
    description: "Pneumococcal polysaccharide vaccine, 23-valent, adult",
    synonyms: ["pneumonia vaccine", "PPSV23", "Pneumovax"],
    typicalFeeCents: 12000,
  },
  {
    code: "93000",
    description: "Electrocardiogram, 12-lead, with interpretation and report",
    synonyms: ["ECG", "EKG", "12-lead ECG", "electrocardiogram"],
    typicalFeeCents: 5500,
  },
  {
    code: "71046",
    description: "Chest X-ray, 2 views",
    synonyms: ["CXR 2 views", "chest x-ray", "chest xray PA and lateral"],
    typicalFeeCents: 9500,
  },
  {
    code: "73562",
    description: "X-ray, knee, 3 views",
    synonyms: ["knee x-ray 3 views", "knee xray", "knee films"],
    typicalFeeCents: 9000,
  },
  {
    code: "94010",
    description: "Spirometry",
    synonyms: ["spirometry", "pulmonary function test", "PFT, simple"],
    typicalFeeCents: 8500,
  },
  {
    code: "12001",
    description: "Simple repair of superficial wound, 2.5 cm or less",
    synonyms: ["simple laceration repair", "simple repair", "lac repair 2.5 cm or less"],
    typicalFeeCents: 22000,
  },
  {
    code: "20610",
    description: "Arthrocentesis/injection, major joint or bursa",
    synonyms: ["joint injection", "knee injection", "joint aspiration", "arthrocentesis"],
    typicalFeeCents: 17500,
  },
  {
    code: "17110",
    description: "Destruction of benign lesions, up to 14",
    synonyms: ["wart removal", "cryotherapy, benign lesions", "wart destruction"],
    typicalFeeCents: 15000,
  },
  {
    code: "69210",
    description: "Removal of impacted cerumen, unilateral",
    synonyms: ["ear wax removal", "cerumen removal", "cerumen disimpaction"],
    typicalFeeCents: 8000,
  },
  {
    code: "10060",
    description: "Incision and drainage of abscess, simple",
    synonyms: ["I&D", "abscess drainage", "incision and drainage"],
    typicalFeeCents: 20000,
  },
  {
    code: "96372",
    description: "Therapeutic injection, subcutaneous or intramuscular",
    synonyms: ["IM injection", "therapeutic injection", "injection admin"],
    typicalFeeCents: 3500,
  },
  {
    code: "99406",
    description: "Smoking cessation counseling, 3-10 minutes",
    synonyms: ["smoking cessation counseling", "tobacco counseling", "smoking cessation, brief"],
    typicalFeeCents: 2500,
  },
];
